upgrade

diff --git a/packages/git/packaging b/packages/git/packaging
--- a/packages/git/packaging
+++ b/packages/git/packaging
@@ -1,13 +1,18 @@
-# abort script on any command that exit with a non zero value
-set -e
+set -e # exit immediately if a simple command exits with a non-zero status
+set -u # report the usage of uninitialized variables
 
-tar xzf git/git-1.8.4.tar.gz
+# Detect # of CPUs so make jobs can be parallelized
+CPUS=$(grep -c ^processor /proc/cpuinfo)
+ # Available variables
+# $BOSH_COMPILE_TARGET - where this package & spec'd source files are available
+# $BOSH_INSTALL_TARGET - where you copy/install files to be included in package
+export HOME=/var/vcap
 
-export HOME=/home/vcap
 
-(
-  cd git-1.8.4
-  ./configure --prefix=${BOSH_INSTALL_TARGET}
-  make
-  make install
-)
+
+tar xfv git/git-1.9.0.tar.gz
+cd git-1.9.0
+./configure --prefix=${BOSH_INSTALL_TARGET}
+make -j${CPUS} && make install
+# Alternatively, to copy archive contents:
+# cp -a git-1.9.0/* $BOSH_INSTALL_TARGET
